import bcrypt from "bcrypt";

import database from "./database";
import Booking from "./entities/Booking";
import Equipment from "./entities/Equipment";
import Housing from "./entities/Housing";
import Rating from "./entities/Rating";
import User from "./entities/User";

export default async function insertDefaultDatbaseContent() {
  const entities_names = database.entityMetadatas.map(entity => '"' + entity.tableName + '"').join(", ");
  console.log("TRUNCATE " + entities_names + " CASCADE;");
  await database.query("TRUNCATE " + entities_names + " CASCADE;");

  const users = database.getRepository(User);
  const equipments = database.getRepository(Equipment);
  const housings = database.getRepository(Housing);
  const bookings = database.getRepository(Booking);
  const ratings = database.getRepository(Rating);


  const equipment_list = [
    "Equipements de sports d'hiver",
    "Jacuzzi",
    "Jardin",
    "Parc de jeux",
    "Spa",
    "Centre équestre",
    "Golf",
    "Piscine",
    "Tennis",
    "Bateau à moteur",
    "Bateau à voile",
    "Patinoire",
    "Equipements de plongée.",
    "Piste de Bobsleigh",
  ];

  for (const equipment of equipment_list) {
    await equipments.insert({ name: equipment });
  }

  const housing_list = [
    {
      name: "Nid de Chouette",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/050afba036faed30c9de4690682c265f.jpg"],
      area: "Gap",
      description: "Se lever à l’aurore, aller chercher le soleil qui se lève sur les sommets",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 200,
      bedroom_count: 8,
      bathroom_count: 3,
      chef: "Forfait sur mesure",
      equipments: ["Equipements de sports d'hiver", "Jacuzzi", "Jardin", "Parc de jeux", "Spa"],
      category: "Montagne",
      type: "Chalet"
    },
    {
      name: "La Galibe",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/1mns73s41dqvdwddf57tqre8tlz8k93tm1hkd3t18.jpg"],
      area: "Malestroit",
      description: "Terre de Chouans!",
      low_price: 3000,
      medium_price: 5000,
      high_price: 8000,
      surface: 300,
      bedroom_count: 10,
      bathroom_count: 5,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Golf", "Jardin", "Parc de jeux", "Piscine", "Spa", "Tennis"],
      category: "Campagne",
      type: "Maison"
    },
    {
      name: "Les Roches",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/0wh455.jpg"],
      area: "Les Sables d’Olonne",
      description: "Bercée par les flots, cette villa vous promet des moments enchanteurs.",
      low_price: 4000,
      medium_price: 6000,
      high_price: 9000,
      surface: 400,
      bedroom_count: 6,
      bathroom_count: 2,
      chef: "Forfait sur mesure",
      equipments: ["Bateau à moteur", "Bateau à voile", "Centre équestre", "Jacuzzi", "Jardin", "Parc de jeux", "Piscine", "Spa"],
      category: "Bord de mer",
      type: "Villa"
    },
    {
      name: "Maison des Rives",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/06l0bb21pxgl07i0zhhhm25oenjh7pvvkb27bjags.jpg"],
      area: "Sarlat",
      description: "Au coeur du périgord noir, pour des vacances gastronomiques et sportives! Idéal pour les familles!",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 190,
      bedroom_count: 6,
      bathroom_count: 3,
      chef: "Forfait sur mesure",
      equipments: ["Jacuzzi", "Jardin", "Parc de jeux", "Piscine", "Tennis"],
      category: "Campagne",
      type: "Maison"
    },
    {
      name: "Les Cimes",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/640x480_554133-lodge_ete_12014.jpg"],
      area: "Chambéry",
      description: "Une vue révee sur les sommets, un spa de luxe caché dans ses murs, des balades équestres en montagne. Un lieu parfait pour se détendre",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 200,
      bedroom_count: 8,
      bathroom_count: 4,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Equipements de sports d'hiver", "Jacuzzi", "Jardin", "Parc de jeux", "Spa"],
      category: "Montagne",
      type: "Chalet"
    },
    {
      name: "Les Landes",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/Bazas.png"],
      area: "Bazas",
      description: "Notre chef local excelle dans la préparation du boeuf de Bazas",
      low_price: 3000,
      medium_price: 5000,
      high_price: 8000,
      surface: 300,
      bedroom_count: 10,
      bathroom_count: 5,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Golf", "Jacuzzi", "Jardin", "Parc de jeux", "Piscine"],
      category: "Campagne",
      type: "Manoir"
    },
    {
      name: "Snowbeach",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/640x480_megeve-location-chalet-luxe-taxozite-piscine-13422.jpg"],
      area: "Mégève",
      description: "Pour les fans de glisse!!!",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 200,
      bedroom_count: 8,
      bathroom_count: 4,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Equipements de sports d'hiver", "Jardin", "Spa", "Tennis"],
      category: "Montagne",
      type: "Villa"
    },
    {
      name: "Yololoiou",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/1605-Batieu-180927-JG-16-EU-RJ.jpg"],
      area: "Alpes suisses",
      description: "Authentique! AU coeur des Alpes suisses,, avec un contact heureux avec le folklore local!",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 200,
      bedroom_count: 8,
      bathroom_count: 4,
      chef: "Forfait sur mesure",
      equipments: ["Equipements de sports d'hiver", "Jacuzzi", "Jardin", "Parc de jeux", "Patinoire", "Spa"],
      category: "Montagne",
      type: "Chalet"
    },
    {
      name: "Lavande",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/6086cb70306fd.jpg"],
      area: "Saint Paul de Vence",
      description: "Cézanne y a vécu, pour y peindre l’Estaque",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 190,
      bedroom_count: 6,
      bathroom_count: 3,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Golf", "Jardin", "Parc de jeux", "Piscine", "Spa", "Tennis"],
      category: "Campagne",
      type: "Maison"
    },
    {
      name: "Les vents d’ouest",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/27061_00-2021-11-10-0148.jpg"],
      area: "Carnac",
      description: "Une villa pour vous sentir riches...ou juste pour passer un moment délicieux en famille!",
      low_price: 4000,
      medium_price: 6000,
      high_price: 9000,
      surface: 400,
      bedroom_count: 15,
      bathroom_count: 10,
      chef: "Forfait sur mesure",
      equipments: ["Bateau à moteur", "Equipements de plongée.", "Jacuzzi", "Jardin", "Piscine"],
      category: "Bord de mer",
      type: "Villa"
    },
    {
      name: "La maison dans les bois",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/21240-france-les-tournels.jpg"],
      area: "Luz Saint Sauveur",
      description: "Vous ne vous arrêterez pas ici, vous vous équiperez et partirez à l’assaut des cimes!",
      low_price: 1500,
      medium_price: 2500,
      high_price: 3500,
      surface: 110,
      bedroom_count: 4,
      bathroom_count: 2,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Jacuzzi", "Jardin", "Parc de jeux"],
      category: "Ville",
      type: "Atypique"
    },
    {
      name: "Guarrigue",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/0871_Source_JG_180529_01_EU.jpg"],
      area: "Saint Maximin",
      description: "Monter sur la Sainte Victoire et voir la mer, une fois dans sa vie! Savourer le beurre de truffe lors d’apéritifs trainants!",
      low_price: 3000,
      medium_price: 5000,
      high_price: 8000,
      surface: 300,
      bedroom_count: 10,
      bathroom_count: 5,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Golf", "Jacuzzi", "Jardin", "Piscine", "Spa", "Tennis"],
      category: "Campagne",
      type: "Villa"
    },
    {
      name: "Le Pic",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/111904-2.jpg"],
      area: "Gavarnie",
      description: "Qui n’a jamais vu le cirque de Gavarnie n’a pas vécu!",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 180,
      bedroom_count: 6,
      bathroom_count: 3,
      chef: "Forfait sur mesure",
      equipments: ["Equipements de sports d'hiver", "Jacuzzi", "Jardin", "Piste de Bobsleigh", "Spa"],
      category: "Montagne",
      type: "Chalet"
    },
    {
      name: "L’alpage",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/265473276.jpg"],
      area: "Voiron",
      description: "La douceur des premières pentes, le repos de l’âme!",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 200,
      bedroom_count: 7,
      bathroom_count: 4,
      chef: "Forfait sur mesure",
      equipments: ["Equipements de sports d'hiver", "Jacuzzi", "Jardin", "Parc de jeux", "Patinoire", "Spa"],
      category: "Montagne",
      type: "Maison"
    },
    {
      name: "Villa Berthe",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/chic-villas-brittany-emeraude-g1.jpg"],
      area: "Granville",
      description: "Son bateau à moteur dernier cri pour de superbes balades sur Chausey et Jersey",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 190,
      bedroom_count: 6,
      bathroom_count: 3,
      chef: "Forfait sur mesure",
      equipments: ["Jacuzzi", "Jardin", "Parc de jeux", "Piscine", "Tennis"],
      category: "Campagne",
      type: "Maison"
    },
    {
      name: "Villa des Pins",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/lagapa-perros-guirec-crdit-kelly-martos-5-640x360-crop-1579247128.jpg"],
      area: "La Roche sur Yon",
      description: "Cette maison, à deux pas de la plage, a vu passer Jean Rochefort, Lino Ventura, Gérard Depardieu. Tous la conseillent!",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 200,
      bedroom_count: 7,
      bathroom_count: 4,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Jacuzzi", "Jardin", "Parc de jeux", "Piscine"],
      category: "Bord de mer",
      type: "Villa"
    },
    {
      name: "Villa les Murets",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/d4.jpg"],
      area: "Rocamadour",
      description: "Rocamadour, terre de miracles!",
      low_price: 4000,
      medium_price: 6000,
      high_price: 9000,
      surface: 400,
      bedroom_count: 12,
      bathroom_count: 8,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Golf", "Jacuzzi", "Jardin", "Parc de jeux", "Piscine"],
      category: "Campagne",
      type: "Villa"
    },
    {
      name: "Villa Sémaphore",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/istockphoto-1175468826-612x612.jpg"],
      area: "Oléron",
      description: "Le charme de l’authentique, l’appel de la mer",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 180,
      bedroom_count: 6,
      bathroom_count: 3,
      chef: "Forfait sur mesure",
      equipments: ["Bateau à moteur", "Bateau à voile", "Equipements de plongée.", "Jardin", "Parc de jeux", "Spa"],
      category: "Bord de mer",
      type: "Atypique"
    },
    {
      name: "Villa Basque",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/les-maisons-avec-vue-sur-mer-comme-ici-a-groix-sont_4776968_676x338p_(1).jpg"],
      area: "Mimizan",
      description: "Pour la Feria, à deux pas de Bayonne!",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 200,
      bedroom_count: 7,
      bathroom_count: 4,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Jardin", "Parc de jeux", "Piscine", "Spa"],
      category: "Bord de mer",
      type: "Maison"
    },
    {
      name: "La Cabane",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/location-gite-haut-de-gamme-scaled.jpg"],
      area: "Cahors",
      description: "Un nid parfait pour renouveler votre amour!",
      low_price: 1500,
      medium_price: 2500,
      high_price: 3500,
      surface: 110,
      bedroom_count: 4,
      bathroom_count: 2,
      chef: "Forfait sur mesure",
      equipments: ["Golf", "Jacuzzi", "Jardin", "Piscine", "Spa", "Tennis"],
      category: "Campagne",
      type: "Atypique"
    },
    {
      name: "Vue sur Mer",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/maison-avec-vue-mer.jpg"],
      area: "Dinard",
      description: "So British!",
      low_price: 1000,
      medium_price: 1500,
      high_price: 2000,
      surface: 75,
      bedroom_count: 3,
      bathroom_count: 2,
      chef: "Forfait sur mesure",
      equipments: ["Bateau à moteur", "Bateau à voile", "Centre équestre", "Equipements de plongée.", "Jacuzzi", "Jardin", "Parc de jeux"],
      category: "Bord de mer",
      type: "Appartement"
    },
    {
      name: "Villa Trappeur",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/location-vacances-chalet-la-bresse-465103-7.jpeg"],
      area: "Annecy",
      description: "Vous sentez-vous prêts pour l’aventure? Programme proposé sur mesure",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 200,
      bedroom_count: 7,
      bathroom_count: 3,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Equipements de sports d'hiver", "Jardin", "Spa"],
      category: "Montagne",
      type: "Chalet"
    },
    {
      name: "La Malouine",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/meuble-maison-de-maitre-de-perier-85200-fontenay-le-comte-1.jpg"],
      area: "Saint Malo",
      description: "Vous sentez-vous une âme d’armateur? Surcouf y est passé!",
      low_price: 4000,
      medium_price: 6000,
      high_price: 9000,
      surface: 380,
      bedroom_count: 14,
      bathroom_count: 8,
      chef: "Forfait sur mesure",
      equipments: ["Bateau à moteur", "Bateau à voile", "Centre équestre", "Equipements de plongée.", "Jacuzzi", "Jardin", "Parc de jeux", "Piscine", "Spa"],
      category: "Bord de mer",
      type: "Manoir"
    },
    {
      name: "Spa des Alpes",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/salon-chalet-luxe-serre-che.jpg"],
      area: "Briançon",
      description: "Se reposer, se détendre, profiter, aimer!!",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 190,
      bedroom_count: 6,
      bathroom_count: 3,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Equipements de sports d'hiver", "Jacuzzi", "Jardin", "Parc de jeux", "Patinoire", "Piste de Bobsleigh", "Spa"],
      category: "Montagne",
      type: "Chalet"
    },
    {
      name: "Villa des Vignes",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/unnamed_(3).jpg"],
      area: "Blaye",
      description: "Un verre de Saint Estèphe 1998, au coin du feu le soir ou sur la terrasse le midi, pendant que dorent les poissons sur la plancha....",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 210,
      bedroom_count: 8,
      bathroom_count: 3,
      chef: "Forfait sur mesure",
      equipments: ["Bateau à moteur", "Bateau à voile", "Centre équestre", "Equipements de plongée.", "Jacuzzi", "Jardin", "Parc de jeux", "Piscine", "Spa"],
      category: "Bord de mer",
      type: "Villa"
    },
    {
      name: "Villa Margeride",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/unnamed_(2).jpg"],
      area: "Saint Flour",
      description: "Saint Flour, cité des grands vents! A visiter absolument! A deux pas des monts du Cantal et du GR400!",
      low_price: 3000,
      medium_price: 5000,
      high_price: 8000,
      surface: 300,
      bedroom_count: 16,
      bathroom_count: 8,
      chef: "Forfait sur mesure",
      equipments: ["Bateau à moteur", "Bateau à voile", "Centre équestre", "Equipements de plongée.", "Equipements de sports d'hiver", "Jacuzzi", "Jardin", "Parc de jeux", "Piscine", "Spa"],
      category: "Montagne",
      type: "Villa"
    },
    {
      name: "Buron des Cimes",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/swimming-pool.jpg"],
      area: "Serre-Chevalier",
      description: "Le luxe au coeur des montagnes!",
      low_price: 8000,
      medium_price: 11000,
      high_price: 15000,
      surface: 600,
      bedroom_count: 20,
      bathroom_count: 20,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Equipements de sports d'hiver", "Jacuzzi", "Jardin", "Parc de jeux", "Spa"],
      category: "Montagne",
      type: "Villa"
    },
    {
      name: "Belle époque",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/unnamed_(1).jpg"],
      area: "Fontainebleau",
      description: "Le faste des Rois. Joséphine de Beauharnais y a résidé",
      low_price: 3000,
      medium_price: 5000,
      high_price: 8000,
      surface: 270,
      bedroom_count: 10,
      bathroom_count: 6,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Golf", "Jardin", "Piscine", "Tennis"],
      category: "Ville",
      type: "Manoir"
    },
    {
      name: "Villa Normande",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/unnamed.jpg"],
      area: "Honfleur",
      description: "Coup de coeur! ma famille y a vécu pendant trois générations, les murs ont une histoire!",
      low_price: 3000,
      medium_price: 5000,
      high_price: 8000,
      surface: 280,
      bedroom_count: 10,
      bathroom_count: 5,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Golf", "Jacuzzi", "Jardin", "Piscine", "Spa", "Tennis"],
      category: "Campagne",
      type: "Villa"
    },
    {
      name: "Villa des Puys",
      images_urls: ["Catalogue%20b1708c8345b34bfdb1cd22a8554d8b6e/1fcak8163jr3xmm42ghm5hgua0vjwdn7y1jxz0lj4.jpg"],
      area: "Chamaliéres",
      description: "Clermont-Ferrand, cité des Volcans. Les puys à deux pas pour des balades enchanteresses! Vous profiterez aussi des thermes de Royat et Chatel Guyon, pour des vacances ressourçantes!",
      low_price: 2000,
      medium_price: 4000,
      high_price: 5000,
      surface: 200,
      bedroom_count: 7,
      bathroom_count: 4,
      chef: "Forfait sur mesure",
      equipments: ["Centre équestre", "Jardin", "Tennis"],
      category: "Ville",
      type: "Manoir"
    },
  ];

  for (let housing of housing_list) {
    housings.insert({
      name: housing.name,
      images_urls: housing.images_urls,
      area: housing.area,
      description: housing.description,
      low_price: housing.low_price,
      medium_price: housing.medium_price,
      high_price: housing.high_price,
      surface: housing.surface,
      bedroom_count: housing.bedroom_count,
      bathroom_count: housing.bathroom_count,
      chef: housing.chef,
      category: housing.category,
      type: housing.type,
      equipments: await Promise.all(housing.equipments.map(async equipment_name => {
        const equipment = await equipments.findOneBy({ name: equipment_name });
        if (equipment == null) {
          throw new Error("Unknown equipment when filling database with default content");
        }
        return equipment;
      })),
    });
  }

  users.insert({
    first_name: "Louis",
    last_name: "Le Cam",
    password_hash: await bcrypt.hash("admin", 12),
    email: "admin",
    phone_number: "0123456789",
    admin: true,
    bookings: []
  });
}

